name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build and Push Image
  inputs: 
    command: buildAndPush
    Dockerfile: src/EventHorizon.Game.Server.Asset/Dockerfile
    containerRegistry: docker-hub
    buildContext: $(Build.SourcesDirectory)
    repository: canhorn/ehz-platform-server-asset
    tags: |
      latest
      $(Build.BuildNumber)
