name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build Image - EventHorizon.Game.Server.Asset
  inputs: 
    command: build
    containerRegistry: docker-hub
    repository: canhorn/ehz-platform-server-asset
    buildContext: $(Build.SourcesDirectory)
    arguments: --build-arg BUILD_VERSION=$(Build.BuildNumber)
    tags: |
      latest
      $(Build.BuildNumber)

- task: Docker@2
  displayName: Push Image - EventHorizon.Game.Server.Asset 
  inputs: 
    command: push
    containerRegistry: docker-hub
    repository: canhorn/ehz-platform-server-asset
    buildContext: $(Build.SourcesDirectory)
    tags: |
      latest
      $(Build.BuildNumber)
